### ISSUE TITLE
When saving cursor moves to the top of the file

### ISSUE THREAD

**Issue by devmondo** [ideaconnect/vs-trim-line-ends-on-save-plugin#1]
hi, 
awesome work, but when i save the file, visual studio moves the cursor to the top of the file, hence  i lose my editing position and have to scroll back to it.

thanks in advanced.

**Comment by bpacholek** [comment]
@devmondo that is a good suggestion of course! Somebody on Visual Studio Gallery suggested it too - and me myself start to find such thing useful :)

I will implement it ASAP this week :).

Cheers!

**Comment by devmondo** [comment]
@ideaconnect 

thank you man for the effort, i really love this extension, you can also add ability to auto format the document when saving, this will be more awesome :)

**Comment by bpacholek** [comment]
@devmondo cursor position now kept :)

Next update I plan to give an option to enforce line-ending per file type.

**Comment by bpacholek** [comment]
@devmondo now scroll is kept too.

Additionally I have added an options page under Settings -> Text Editor -> Trim on save which allows to select the desired line endings format:

Unix, Windows or:
"VisualStudio" - use standard Environment.NewLine symbol
"Current" - use the ones already in the file

**Comment by devmondo** [comment]
@ideaconnect 
i have tried it, it works perfectly thank you very much, but there is an issue still, which is when you save and remove the extra space the cursor should fallback to last character in the editor, here is example below
now after saving

```
    <div ng-controller="sampleController as vm">
        <input type="button" name="name" value="send " ng-click="vm.addTask()"/>
    </div>  |cursor fallback here
```

it should stop after the last ">"

```
    <div ng-controller="sampleController as vm">
        <input type="button" name="name" value="send " ng-click="vm.addTask()"/>
    </div>|cursor should fall back here
```

also is there a possibility to make the extension available in VS 14 :)

**Comment by bpacholek** [comment]
@devmondo I believe the mentioned issue is now fixed too. Changed the manifest to allow installations in newer versions than Visual Studio 2013. Tested with Visual Studio 2015 Preview (Visual Studio 14).

**Comment by devmondo** [comment]
@ideaconnect  awesome man, i confirm it is working perfectly now :)

**Comment by bpacholek** [comment]
Solved, confirmed by the reporter.
