### ISSUE TITLE
Visual studio 2015 install breaks TextEditor options

### ISSUE THREAD

**Issue by davidhunter22** [ideaconnect/vs-trim-line-ends-on-save-plugin#2]
When I install on VS 2015 the Tools -> Options -> Text Editor options mostly disappear. The menu item this plug in adds appears but things like "All Languages" and and the language specific options disappear from the menu.

**Comment by bpacholek** [comment]
I confirm, sorry for the issue.

Did the simplest thing now: moved the options to a dedicated ("IDCT") group.

Thanks for pointing out!
